export const mockCourses = [
  {
    id: 1,
    title: "ChatGPT Pro Training",
    description: "Learn prompt engineering and AI integrations",
    instructor: "Али Шахбаз",
    instructorAvatar: "https://c.animaapp.com/m9jqfbic8vZpku/img/icon-1.png",
    price: "1,5 $",
    duration: "13:31",
    timeIcon: "https://c.animaapp.com/m9jqfbic8vZpku/img/time-icon-3.png",
    image: "https://c.animaapp.com/m9jqfbic8vZpku/img/box-img-1.png",
    skills: ["Leadership", "Startup"],
    jobTitles: ["CEO", "CTO"],
    companies: ["Microsoft", "Amazon"],
  },
  {
    id: 2,
    title: "Учебный курс SQL Server",
    description: "Master SQL Server from scratch",
    instructor: "Али Ахмади",
    instructorAvatar: "https://c.animaapp.com/m9jqfbic8vZpku/img/icon.png",
    price: "1,5 $",
    duration: "1:37",
    timeIcon: "https://c.animaapp.com/m9jqfbic8vZpku/img/time-icon-3.png",
    image: "https://c.animaapp.com/m9jqfbic8vZpku/img/box-img.png",
    skills: ["Product Management"],
    jobTitles: ["Senior Software Engineer"],
    companies: ["Google"],
  },
  {
    id: 3,
    skills: ["Product Management", "Career Growth"],
    title: "Усовершенствованное ...",
    description: "Lorem ipsum сфабриковал текст с . . .",
    image: "https://c.animaapp.com/m9jqfbic8vZpku/img/box-img-3.png",
    instructor: "Абольфазл Аббаси",
    instructorAvatar: "https://c.animaapp.com/m9jqfbic8vZpku/img/icon-3.png",
    price: "1,5 $",
    duration: "1:31",
    timeIcon: "https://c.animaapp.com/m9jqfbic8vZpku/img/time-icon-3.png",
  },
  {
    id: 4,
    skills: ["Career Growth"],
    title: "Tailwind CSS",
    description: "Lorem ipsum сфабриковал текст с . . .",
    image: "https://c.animaapp.com/m9jqfbic8vZpku/img/box-img-2.png",
    instructor: "Хасан Хосроверди",
    instructorAvatar: "https://c.animaapp.com/m9jqfbic8vZpku/img/icon-2.png",
    price: "1,5 $",
    duration: "1:31",
    timeIcon: "https://c.animaapp.com/m9jqfbic8vZpku/img/time-icon-2.png",
  },
  {
    id: 5,
    title: "Учебники по Python",
    description: "Lorem ipsum сфабриковал текст с . . .",
    image: "https://c.animaapp.com/m9jqfbic8vZpku/img/box-img-5.png",
    instructor: "Али Шахбаз",
    instructorAvatar: "https://c.animaapp.com/m9jqfbic8vZpku/img/icon-5.png",
    price: "Бесплатно!",
    duration: "1:31",
    timeIcon: "https://c.animaapp.com/m9jqfbic8vZpku/img/time-icon-5.png",
  },
  {
    id: 6,
    title: "Asp . net core",
    description: "Lorem ipsum сфабриковал текст с . . .",
    image: "https://c.animaapp.com/m9jqfbic8vZpku/img/box-img-4.png",
    instructor: "Али Шахбаз",
    instructorAvatar: "https://c.animaapp.com/m9jqfbic8vZpku/img/icon-4.png",
    price: "1,5 $",
    duration: "1:31",
    timeIcon: "https://c.animaapp.com/m9jqfbic8vZpku/img/time-icon-4.png",
  },
];
